package com.project.cart;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.project.courses.Course;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Entity
@Table
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Cart implements Serializable
{
	private static final long serialVersionUID = 6321436223736954919L;
	
	@Id
	@GeneratedValue
	@ApiModelProperty(value = "Autogenerated Id")
	private int itemId;
	
	@ManyToOne
	@JoinColumn(name = "course_id", referencedColumnName = "courseId")
	Course course;

	public int getItemId() {
		return itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public Course getCourse() {
		return course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}
}